Autocomplete search
N-Viet-ruby-dev/Rubynary pull request #19
Opened 2019-07-26 03:54 UTC by nguyenvanhung1995

2019-07-26 08:02 UTC, ngocnguyenbk approved these changes
Oke

2019-07-26 08:03 UTC, DuyNguyen05 approved these changes

2019-07-29 06:17 UTC, luongvietdung commented on app/assets/stylesheets/easy-autocomplete.css
> +/*
move this file to `vendor`

2019-07-29 06:19 UTC, luongvietdung commented on app/controllers/words_controller.rb
> +    if @words.count.zero?
`count.zero?` --> `empty?`

2019-07-29 06:20 UTC, luongvietdung commented on app/assets/stylesheets/easy-autocomplete.themes.css
> +/*
move this file to vendor/assets/stylesheets

2019-07-29 06:21 UTC, luongvietdung commented on app/views/words/index.js.erb
> +$("#pagination").html("<%= j paginate(@words, remote: true) %>");
Cái này sao lịa phải đổi như vậy?

2019-07-29 06:22 UTC, luongvietdung commented on app/controllers/words_controller.rb
> +          @words = @words.limit(9)
Sao lại limt 9

2019-07-29 06:36 UTC, nguyenvanhung1995 commented on app/controllers/words_controller.rb
> +          @words = @words.limit(9)
Để giới hạn số gợi í hiện ra khi gõ vào ô tìm kiếm a ạ.

2019-08-01 02:19 UTC, luongvietdung requested changes

2019-08-01 02:19 UTC, luongvietdung commented on app/assets/javascripts/application.js
> +//= require turbolinks
Bỏ turbolinks đi em

2019-08-01 02:31 UTC, nguyenvanhung1995 commented on app/assets/javascripts/application.js
> +//= require turbolinks
Bỏ thì autocomplete nó ko chạy a ạ :3

2019-08-01 06:03 UTC, luongvietdung requested changes

2019-08-01 06:03 UTC, luongvietdung commented on app/assets/javascripts/search.js
> +$(document).on('turbolinks:load', function () {
Em đổi cái này thành ready thì sẽ chạy

2019-08-01 06:03 UTC, luongvietdung commented on app/assets/javascripts/application.js
> +//= require turbolinks
Phải tìm hiểu xem vì sao không chạy chứ

2019-08-02 02:49 UTC, luongvietdung commented on app/controllers/words_controller.rb
> +          @words = @words.limit(9)
Đặt số 9 thành hằng số đi

2019-08-02 02:56 UTC, nguyenvanhung1995 commented on app/controllers/words_controller.rb
> +          @words = @words.limit(9)
@number_results = 9;
@words = @words.limit(@number_results)
kiểu thế này hả anh

2019-08-02 03:29 UTC, nguyenvanhung1995 commented on app/controllers/words_controller.rb
> +          @words = @words.limit(9)
Đã sửa, bật ngrok rồi ạ.

2019-08-02 11:58 UTC, luongvietdung commented on app/assets/javascripts/jquery.easy-autocomplete.js
> +var EasyAutocomplete = (function(scope){
De vao vendor/assets/javascript di chu

2019-08-05 06:22 UTC, luongvietdung approved these changes

2019-08-05 06:22 UTC, merged